name: linux-build

on:
  pull_request:
  workflow_dispatch:

jobs:

  check-diff:
    runs-on: ubuntu-latest
    outputs: 
      handle: ${{ steps.check.outputs.run }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 2

      # The goal is to force this to pass if it does not need to run.
      - name: Check the diff
        id: check
        run: |
          echo "Here are the changed build/C files:"
          echo "$(git --no-pager diff --name-only HEAD HEAD~1 | grep -E '\.(c|h)$|\.cmake|CMakeLists|Config\.cmake\.in')"
          if git --no-pager diff --name-only HEAD HEAD~1 | grep -qE '\.(c|h)$|\.cmake|CMakeLists|Config\.cmake\.in'; then
            echo "run=true" >> $GITHUB_OUTPUT
            echo "Implementation and/or build files have changed, rebuilding..."
          else
            echo "run=false" >> $GITHUB_OUTPUT
            echo "Implementation and/or build files have NOT changed, skipping build..."
          fi

  build:
    runs-on: ubuntu-latest
    name: Clang Linux-x64 ${{ matrix.build == 'debug' && 'Debug' || 'Release' }} - ${{ matrix.portable == 'ON' && 'Portable SRMD Flat Hash Map' || 'Platform SIMD Flat Hash Map' }}
    needs: check-diff
    if: ${{ needs.check-diff.outputs.handle == 'true' }}
    env:
      LLVM_PREFIX: LLVM
      LLVM_VERSION: 22.1.0
      LLVM_PLATFORM: Linux-X64
    strategy:
      matrix:
        build: [debug, release]
        portable: [OFF, ON]

    steps:

    - name: Sanity Check
      run: |
        echo "${{ needs.check-diff.outputs.handle }}"
  
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: lukka/get-cmake@latest
    
    - name: Cache LLVM
      id: cache-llvm
      uses: actions/cache@v5
      with:
        path: llvm
        key: ${{env.LLVM_PREFIX}}-${{env.LLVM_VERSION}}-${{env.LLVM_PLATFORM}}

    - name: Download LLVM release
      if: steps.cache-llvm.outputs.cache-hit != 'true'
      run: |
        set -eux
        LLVM_URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-${LLVM_VERSION}/${LLVM_PREFIX}-${LLVM_VERSION}-${LLVM_PLATFORM}.tar.xz"
        curl -L --fail "$LLVM_URL" -o llvm.tar.xz
        mkdir -p llvm
        tar -xvf llvm.tar.xz --strip-components=1 -C llvm

    - name: Confirm Clang version
      run: |
        "$PWD/llvm/bin/clang" --version

    - name: Build and Test with Clang Linux-x64
      run: |
        make clean
        cmake --preset=clang-${{ matrix.build }} -DCCC_BUILD_SPECIALIZED=ON -DCCC_FLAT_HASH_MAP_PORTABLE=${{ matrix.portable }} -DCMAKE_C_COMPILER="$PWD/llvm/bin/clang" -G "Ninja" && cmake --build build -j$(nproc) --target ccc tests samples
        cmake --build build --target install
        make test
