name: tag-release-branch

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release Zip
        run: |
          TAG="${GITHUB_REF#refs/tags/}"

          # Specialized Release with attributes to include specialized/ directories
          git -c core.attributesFile=.gitattributes archive --format=zip --output=ccc-specialized-${TAG}.zip HEAD
          echo "SPECIALIZED_ZIP_FILE=ccc-specialized-${TAG}.zip" >> $GITHUB_ENV

          # Core Release with attributes to exclude specialized/ directories
          git -c core.attributesFile=.gitattributes_core archive --format=zip --output=ccc-${TAG}.zip HEAD
          echo "ZIP_FILE=ccc-${TAG}.zip" >> $GITHUB_ENV 


      - name: Create draft release
        run: |
          gh release create "${GITHUB_REF#refs/tags/}" \
            --draft \
            --title "${GITHUB_REF#refs/tags/}" \
            --notes "Release Notes:"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload asset to draft
        run: |
          gh release upload "${GITHUB_REF#refs/tags/}" "${ZIP_FILE}" "${SPECIALIZED_ZIP_FILE}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        run: |
          gh release edit "${GITHUB_REF#refs/tags/}" --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

